"""
Inference helper for LiveMatch Intelligence match-outcome prediction.

This module loads the calibrated enhanced time-aware models and selects the
appropriate model based on the current replay minute.

Expected model files:
    models/enhanced_time_aware/calibrated/match_outcome_15.joblib
    models/enhanced_time_aware/calibrated/match_outcome_30.joblib
    models/enhanced_time_aware/calibrated/match_outcome_45.joblib
    models/enhanced_time_aware/calibrated/match_outcome_60.joblib
    models/enhanced_time_aware/calibrated/match_outcome_75.joblib
    models/enhanced_time_aware/calibrated/match_outcome_85.joblib

Metadata:
    models/enhanced_time_aware/calibrated/calibrated_enhanced_metadata.joblib

Important:
    These predictions are experimental research estimates based on historical
    StatsBomb match-state snapshots. They should not be described as fully
    calibrated production probabilities.
"""

from pathlib import Path

import joblib
import numpy as np
import pandas as pd

from src.image_fetcher import get_team_badge


PROJECT_ROOT = Path(__file__).resolve().parents[1]

MODEL_DIR = (
    PROJECT_ROOT
    / "models"
    / "enhanced_time_aware"
    / "calibrated"
)

METADATA_FILE = (
    MODEL_DIR
    / "calibrated_enhanced_metadata.joblib"
)

AVAILABLE_MODEL_MINUTES = [15, 30, 45, 60, 75, 85]

CLASS_ORDER = [
    "Home Win",
    "Draw",
    "Away Win",
]


def _normalise_model_minute(match_minute):
    """
    Choose the latest model snapshot that does not exceed the current minute.

    Examples:
        minute 18 -> 15' model
        minute 44 -> 30' model
        minute 60 -> 60' model
        minute 93 -> 85' model

    Before 15', the 15' model is used as an early prototype fallback.
    """
    try:
        minute = int(float(match_minute))
    except (TypeError, ValueError):
        minute = 15

    eligible = [
        model_minute
        for model_minute in AVAILABLE_MODEL_MINUTES
        if model_minute <= minute
    ]

    if eligible:
        return max(eligible)

    return AVAILABLE_MODEL_MINUTES[0]


def _get_model_classes(model):
    if hasattr(model, "classes_"):
        return list(model.classes_)

    if hasattr(model, "named_steps"):
        final_estimator = list(
            model.named_steps.values()
        )[-1]

        if hasattr(
            final_estimator,
            "classes_",
        ):
            return list(
                final_estimator.classes_
            )

    # CalibratedClassifierCV normally exposes classes_ directly.
    raise RuntimeError(
        "Could not determine the model class ordering."
    )


def _align_probabilities(
    model,
    raw_probabilities,
):
    model_classes = _get_model_classes(
        model
    )

    aligned = np.zeros(
        (
            raw_probabilities.shape[0],
            len(CLASS_ORDER),
        ),
        dtype=float,
    )

    for target_index, class_name in enumerate(
        CLASS_ORDER
    ):
        if class_name in model_classes:
            source_index = model_classes.index(
                class_name
            )

            aligned[
                :,
                target_index,
            ] = raw_probabilities[
                :,
                source_index,
            ]

    totals = aligned.sum(
        axis=1,
        keepdims=True,
    )

    totals[
        totals == 0
    ] = 1.0

    return (
        aligned / totals
    )


def load_prediction_metadata():
    """
    Load calibration metadata generated by
    calibrate_enhanced_time_aware_models.py.
    """
    if not METADATA_FILE.exists():
        raise FileNotFoundError(
            f"Prediction metadata not found: {METADATA_FILE}"
        )

    return joblib.load(
        METADATA_FILE
    )


def load_model_for_minute(
    match_minute,
):
    """
    Load the calibrated enhanced model appropriate for the replay minute.
    """
    model_minute = _normalise_model_minute(
        match_minute
    )

    model_file = (
        MODEL_DIR
        / f"match_outcome_{model_minute}.joblib"
    )

    if not model_file.exists():
        raise FileNotFoundError(
            f"Prediction model not found: {model_file}"
        )

    model = joblib.load(
        model_file
    )

    return (
        model,
        model_minute,
    )


def build_enhanced_match_state_features(
    base_features,
):
    """
    Recreate the enhanced feature engineering used during training.

    Parameters
    ----------
    base_features : dict
        Dictionary containing the current match-state features.

    Returns
    -------
    dict
        Original features plus the engineered contextual features.
    """

    row = dict(
        base_features
    )

    minute = float(
        row.get(
            "snapshot_minute",
            0.0,
        )
    )

    home_goals = float(
        row.get(
            "home_goals",
            0.0,
        )
    )

    away_goals = float(
        row.get(
            "away_goals",
            0.0,
        )
    )

    goal_difference = float(
        row.get(
            "goal_difference",
            home_goals - away_goals,
        )
    )

    home_xg = float(
        row.get(
            "home_xg",
            0.0,
        )
    )

    away_xg = float(
        row.get(
            "away_xg",
            0.0,
        )
    )

    xg_difference = float(
        row.get(
            "xg_difference",
            home_xg - away_xg,
        )
    )

    home_shots = float(
        row.get(
            "home_shots",
            0.0,
        )
    )

    away_shots = float(
        row.get(
            "away_shots",
            0.0,
        )
    )

    shot_difference = float(
        row.get(
            "shot_difference",
            home_shots - away_shots,
        )
    )

    home_pressures = float(
        row.get(
            "home_pressures",
            0.0,
        )
    )

    away_pressures = float(
        row.get(
            "away_pressures",
            0.0,
        )
    )

    pressure_difference = float(
        row.get(
            "pressure_difference",
            home_pressures
            - away_pressures,
        )
    )

    home_recent_xg = float(
        row.get(
            "home_recent_xg",
            0.0,
        )
    )

    away_recent_xg = float(
        row.get(
            "away_recent_xg",
            0.0,
        )
    )

    home_recent_shots = float(
        row.get(
            "home_recent_shots",
            0.0,
        )
    )

    away_recent_shots = float(
        row.get(
            "away_recent_shots",
            0.0,
        )
    )

    home_recent_pressures = float(
        row.get(
            "home_recent_pressures",
            0.0,
        )
    )

    away_recent_pressures = float(
        row.get(
            "away_recent_pressures",
            0.0,
        )
    )

    momentum_difference = float(
        row.get(
            "momentum_difference",
            0.0,
        )
    )

    time_remaining = max(
        0.0,
        90.0 - minute,
    )

    match_progress = min(
        1.0,
        max(
            0.0,
            minute / 90.0,
        ),
    )

    home_leading_flag = int(
        goal_difference > 0
    )

    draw_flag = int(
        goal_difference == 0
    )

    home_trailing_flag = int(
        goal_difference < 0
    )

    home_xg_per_shot = (
        home_xg / home_shots
        if home_shots > 0
        else 0.0
    )

    away_xg_per_shot = (
        away_xg / away_shots
        if away_shots > 0
        else 0.0
    )

    home_goal_conversion = (
        home_goals / home_shots
        if home_shots > 0
        else 0.0
    )

    away_goal_conversion = (
        away_goals / away_shots
        if away_shots > 0
        else 0.0
    )

    home_recent_attack_index = (
        10.0
        * home_recent_xg
        + 4.0
        * home_recent_shots
        + 0.35
        * home_recent_pressures
    )

    away_recent_attack_index = (
        10.0
        * away_recent_xg
        + 4.0
        * away_recent_shots
        + 0.35
        * away_recent_pressures
    )

    recent_attack_difference = (
        home_recent_attack_index
        - away_recent_attack_index
    )

    overall_dominance_index = (
        2.5
        * goal_difference
        + 1.5
        * xg_difference
        + 0.20
        * shot_difference
        + 0.02
        * pressure_difference
        + 0.01
        * momentum_difference
    )

    row.update(
        {
            "time_remaining":
                time_remaining,

            "match_progress":
                match_progress,

            "late_match_flag":
                int(
                    minute >= 75
                ),

            "very_late_match_flag":
                int(
                    minute >= 85
                ),

            "second_half_flag":
                int(
                    minute >= 45
                ),

            "home_leading_flag":
                home_leading_flag,

            "draw_flag":
                draw_flag,

            "home_trailing_flag":
                home_trailing_flag,

            "abs_goal_difference":
                abs(
                    goal_difference
                ),

            "goal_diff_x_progress":
                goal_difference
                * match_progress,

            "goal_diff_x_time_remaining":
                goal_difference
                * time_remaining,

            "lead_protection_pressure":
                home_leading_flag
                * match_progress,

            "comeback_pressure":
                home_trailing_flag
                * match_progress,

            "late_draw_pressure":
                draw_flag
                * int(
                    minute >= 75
                ),

            "home_xg_minus_goals":
                home_xg
                - home_goals,

            "away_xg_minus_goals":
                away_xg
                - away_goals,

            "xg_score_gap_difference":
                (
                    home_xg
                    - home_goals
                )
                - (
                    away_xg
                    - away_goals
                ),

            "xg_diff_x_progress":
                xg_difference
                * match_progress,

            "home_xg_per_shot":
                home_xg_per_shot,

            "away_xg_per_shot":
                away_xg_per_shot,

            "xg_per_shot_difference":
                home_xg_per_shot
                - away_xg_per_shot,

            "home_goal_conversion":
                home_goal_conversion,

            "away_goal_conversion":
                away_goal_conversion,

            "goal_conversion_difference":
                home_goal_conversion
                - away_goal_conversion,

            "home_recent_attack_index":
                home_recent_attack_index,

            "away_recent_attack_index":
                away_recent_attack_index,

            "recent_attack_difference":
                recent_attack_difference,

            "recent_xg_difference":
                home_recent_xg
                - away_recent_xg,

            "recent_shot_difference":
                home_recent_shots
                - away_recent_shots,

            "recent_pressure_difference":
                home_recent_pressures
                - away_recent_pressures,

            "momentum_x_progress":
                momentum_difference
                * match_progress,

            "leading_but_under_pressure":
                int(
                    home_leading_flag
                    and recent_attack_difference < 0
                ),

            "trailing_with_pressure":
                int(
                    home_trailing_flag
                    and recent_attack_difference > 0
                ),

            "draw_with_home_pressure":
                int(
                    draw_flag
                    and recent_attack_difference > 0
                ),

            "draw_with_away_pressure":
                int(
                    draw_flag
                    and recent_attack_difference < 0
                ),

            "overall_dominance_index":
                overall_dominance_index,

            "late_dominance_index":
                overall_dominance_index
                * match_progress,
        }
    )

    return row


def predict_match_outcome(
    match_minute,
    base_features,
):
    """
    Generate experimental outcome probabilities for the current match state.

    Returns a dictionary with:
        - Home Win
        - Draw
        - Away Win
        - model_minute
        - model_variant
        - validation metrics
    """

    metadata = load_prediction_metadata()

    model, model_minute = load_model_for_minute(
        match_minute
    )

    enhanced_features = build_enhanced_match_state_features(
        base_features
    )

    feature_columns = metadata[
        "feature_columns"
    ]

    missing = [
        column
        for column in feature_columns
        if column not in enhanced_features
    ]

    if missing:
        raise ValueError(
            "Current match state is missing model features: "
            + ", ".join(
                missing
            )
        )

    row = pd.DataFrame(
        [
            {
                column:
                    enhanced_features[
                        column
                    ]
                for column in feature_columns
            }
        ]
    )

    probabilities = _align_probabilities(
        model,
        model.predict_proba(
            row
        ),
    )[0]

    minute_metadata = metadata[
        "minutes"
    ].get(
        str(
            model_minute
        ),
        {},
    )

    return {
        "Home Win":
            float(
                probabilities[0]
            ),

        "Draw":
            float(
                probabilities[1]
            ),

        "Away Win":
            float(
                probabilities[2]
            ),

        "model_minute":
            int(
                model_minute
            ),

        "model_variant":
            minute_metadata.get(
                "variant",
                "Unknown",
            ),

        "validation_accuracy":
            minute_metadata.get(
                "accuracy",
            ),

        "validation_macro_f1":
            minute_metadata.get(
                "macro_f1",
            ),

        "validation_log_loss":
            minute_metadata.get(
                "log_loss",
            ),
    }



def _resolve_predictive_team_badge(team_name):
    try:
        badge_path = get_team_badge(
            str(team_name).strip()
        )
        if (
            badge_path is not None
            and Path(badge_path).exists()
        ):
            return Path(badge_path)
    except Exception:
        pass

    return None


def _add_predictive_team_badge(
    fig,
    team_name,
    left,
    bottom,
    width=0.055,
    height=0.055,
):
    badge_path = _resolve_predictive_team_badge(
        team_name
    )

    if badge_path is None:
        return False

    try:
        from PIL import Image as PILImage

        image = PILImage.open(
            badge_path
        ).convert("RGBA")

        badge_ax = fig.add_axes(
            [
                left,
                bottom,
                width,
                height,
            ]
        )

        badge_ax.imshow(
            image
        )
        badge_ax.axis(
            "off"
        )

        return True

    except Exception:
        return False


def build_predictive_intelligence_figure(
    prediction,
    team_names,
    base_features,
    match_minute=None,
    title="PREDICTIVE INTELLIGENCE",
):
    """
    Build a professional match-outcome prediction dashboard.

    Parameters
    ----------
    prediction : dict
        Output returned by predict_match_outcome().
    team_names : sequence
        Two display team names: [home/team 1, away/team 2].
    base_features : dict
        Current match-state features used by the predictor.
    match_minute : int or float, optional
        Display minute. Falls back to base_features['snapshot_minute'].
    title : str
        Figure title.

    Notes
    -----
    Probabilities are experimental research estimates. They are not guaranteed
    outcomes and should not be presented as production-calibrated probabilities.
    """
    import matplotlib.pyplot as plt
    from matplotlib.patches import FancyBboxPatch, Rectangle

    if len(team_names) < 2:
        raise ValueError("team_names must contain two team names.")

    team_1 = str(team_names[0])
    team_2 = str(team_names[1])

    minute = match_minute
    if minute is None:
        minute = base_features.get("snapshot_minute", prediction.get("model_minute", 0))
    try:
        minute = int(float(minute))
    except (TypeError, ValueError):
        minute = int(prediction.get("model_minute", 0) or 0)

    p1 = float(prediction.get("Home Win", 0.0))
    pd = float(prediction.get("Draw", 0.0))
    p2 = float(prediction.get("Away Win", 0.0))
    total = p1 + pd + p2
    if total <= 0:
        p1 = pd = p2 = 1 / 3
    else:
        p1, pd, p2 = p1 / total, pd / total, p2 / total

    home_goals = int(float(base_features.get("home_goals", 0) or 0))
    away_goals = int(float(base_features.get("away_goals", 0) or 0))
    home_xg = float(base_features.get("home_xg", 0.0) or 0.0)
    away_xg = float(base_features.get("away_xg", 0.0) or 0.0)
    home_shots = int(float(base_features.get("home_shots", 0) or 0))
    away_shots = int(float(base_features.get("away_shots", 0) or 0))
    home_pressures = int(float(base_features.get("home_pressures", 0) or 0))
    away_pressures = int(float(base_features.get("away_pressures", 0) or 0))
    home_recent_xg = float(base_features.get("home_recent_xg", 0.0) or 0.0)
    away_recent_xg = float(base_features.get("away_recent_xg", 0.0) or 0.0)
    momentum_diff = float(base_features.get("momentum_difference", 0.0) or 0.0)

    model_minute = prediction.get("model_minute", "N/A")
    variant = prediction.get("model_variant", "Unknown")
    accuracy = prediction.get("validation_accuracy")
    macro_f1 = prediction.get("validation_macro_f1")
    log_loss = prediction.get("validation_log_loss")

    fig = plt.figure(figsize=(16, 10), dpi=140)
    ax = fig.add_axes([0, 0, 1, 1])
    ax.set_axis_off()

    navy = "#10386f"
    blue = "#2878c8"
    light_blue = "#eaf3fb"
    pale = "#f7f9fc"
    dark = "#111111"
    grey = "#666666"
    border = "#bfd0e3"
    draw_colour = "#9aa6b2"

    # Header
    ax.add_patch(Rectangle((0.03, 0.925), 0.94, 0.045, facecolor=navy, edgecolor=navy))
    ax.text(0.05, 0.947, "LIVE MATCH INTELLIGENCE", color="white",
            fontsize=19, fontweight="bold", va="center")
    ax.text(0.95, 0.947, "PREDICTIVE MODEL", color="white",
            fontsize=10, ha="right", va="center")

    ax.text(0.5, 0.885, title, color=navy, fontsize=24,
            fontweight="bold", ha="center")
    ax.text(0.5, 0.852, f"{team_1} {home_goals}  —  {away_goals} {team_2}",
            fontsize=17, fontweight="bold", ha="center", color=dark)
    ax.text(0.5, 0.825,
            f"Match state: {minute}'  |  Model checkpoint: {model_minute}'  |  Variant: {variant}",
            fontsize=10.5, ha="center", color=grey)

    # Team identities with automatic badge resolution.
    _add_predictive_team_badge(
        fig,
        team_1,
        0.085,
        0.798,
        0.060,
        0.060,
    )
    _add_predictive_team_badge(
        fig,
        team_2,
        0.855,
        0.798,
        0.060,
        0.060,
    )

    ax.text(
        0.155,
        0.825,
        team_1.upper(),
        fontsize=10.5,
        fontweight="bold",
        color=navy,
        ha="left",
        va="center",
    )
    ax.text(
        0.845,
        0.825,
        team_2.upper(),
        fontsize=10.5,
        fontweight="bold",
        color=navy,
        ha="right",
        va="center",
    )

    # Outcome probability section
    ax.add_patch(FancyBboxPatch((0.055, 0.645), 0.89, 0.145,
                                boxstyle="round,pad=0.008,rounding_size=0.012",
                                facecolor=pale, edgecolor=blue, linewidth=1.2))
    ax.text(0.5, 0.765, "ESTIMATED MATCH OUTCOME", color=navy,
            fontsize=13, fontweight="bold", ha="center")

    labels = [f"{team_1} Win", "Draw", f"{team_2} Win"]
    probs = [p1, pd, p2]
    colours = [blue, draw_colour, navy]
    xs = [0.21, 0.50, 0.79]
    for x, label, prob, colour in zip(xs, labels, probs, colours):
        ax.text(x, 0.723, f"{prob*100:.1f}%", ha="center", va="center",
                fontsize=26, fontweight="bold", color=colour)
        ax.text(x, 0.690, label, ha="center", va="center",
                fontsize=11, fontweight="bold", color=dark)

    # Stacked probability bar
    bar_x, bar_y, bar_w, bar_h = 0.14, 0.662, 0.72, 0.014
    start = bar_x
    for prob, colour in zip(probs, colours):
        width = bar_w * prob
        ax.add_patch(Rectangle((start, bar_y), width, bar_h,
                               facecolor=colour, edgecolor="none"))
        start += width

    # Match-state evidence cards
    ax.text(0.06, 0.610, "MATCH-STATE EVIDENCE", color=navy,
            fontsize=14, fontweight="bold")
    cards = [
        ("SCORE", f"{home_goals} — {away_goals}",
         f"Goal difference {home_goals-away_goals:+d}"),
        ("xG", f"{home_xg:.2f} — {away_xg:.2f}",
         f"Difference {home_xg-away_xg:+.2f}"),
        ("SHOTS", f"{home_shots} — {away_shots}",
         f"Difference {home_shots-away_shots:+d}"),
        ("PRESSURES", f"{home_pressures} — {away_pressures}",
         f"Difference {home_pressures-away_pressures:+d}"),
        ("RECENT xG", f"{home_recent_xg:.2f} — {away_recent_xg:.2f}",
         f"Difference {home_recent_xg-away_recent_xg:+.2f}"),
    ]
    card_xs = [0.055, 0.238, 0.421, 0.604, 0.787]
    for x, (heading, value, detail) in zip(card_xs, cards):
        ax.add_patch(FancyBboxPatch((x, 0.485), 0.158, 0.095,
                                    boxstyle="round,pad=0.006,rounding_size=0.009",
                                    facecolor="white", edgecolor=border, linewidth=1.0))
        ax.text(x + 0.079, 0.555, heading, ha="center", fontsize=9.5,
                color=navy, fontweight="bold")
        ax.text(x + 0.079, 0.525, value, ha="center", fontsize=15,
                color=dark, fontweight="bold")
        ax.text(x + 0.079, 0.500, detail, ha="center", fontsize=8.2, color=grey)

    # Interpretation
    ax.add_patch(Rectangle((0.055, 0.435), 0.89, 0.032,
                           facecolor=navy, edgecolor=navy))
    ax.text(0.5, 0.451, "ANALYST INTERPRETATION", color="white",
            fontsize=11.5, fontweight="bold", ha="center", va="center")

    max_idx = int(np.argmax(probs))
    favourite = [team_1, "Draw", team_2][max_idx]
    favourite_prob = probs[max_idx] * 100

    if favourite == "Draw":
        lead_sentence = f"The model currently assigns the highest estimate to a draw ({favourite_prob:.1f}%)."
    else:
        lead_sentence = f"The model currently favours {favourite} ({favourite_prob:.1f}%)."

    if home_xg > away_xg:
        xg_sentence = f"{team_1} lead the xG comparison by {home_xg-away_xg:.2f}."
    elif away_xg > home_xg:
        xg_sentence = f"{team_2} lead the xG comparison by {away_xg-home_xg:.2f}."
    else:
        xg_sentence = "The teams are level on xG at this checkpoint."

    if momentum_diff > 0:
        momentum_sentence = f"Recent momentum input favours {team_1}."
    elif momentum_diff < 0:
        momentum_sentence = f"Recent momentum input favours {team_2}."
    else:
        momentum_sentence = "Recent momentum input is balanced."

    ax.add_patch(FancyBboxPatch((0.055, 0.285), 0.89, 0.135,
                                boxstyle="round,pad=0.008,rounding_size=0.012",
                                facecolor=light_blue, edgecolor=blue, linewidth=1.0))
    bullets = [
        lead_sentence,
        f"Current score is {team_1} {home_goals}-{away_goals} {team_2}; {xg_sentence}",
        f"Shot volume is {home_shots}-{away_shots}; {momentum_sentence}",
    ]
    for i, sentence in enumerate(bullets):
        ax.text(0.075, 0.385 - i * 0.038, u"\u2022 " + sentence,
                fontsize=10.2, color=dark, va="top")

    # Validation / model context
    ax.add_patch(Rectangle((0.055, 0.235), 0.89, 0.032,
                           facecolor=navy, edgecolor=navy))
    ax.text(0.5, 0.251, "MODEL VALIDATION CONTEXT", color="white",
            fontsize=11.5, fontweight="bold", ha="center", va="center")

    def metric_text(value, percent=False):
        if value is None:
            return "N/A"
        try:
            value = float(value)
            return f"{value*100:.1f}%" if percent else f"{value:.3f}"
        except (TypeError, ValueError):
            return str(value)

    validation_items = [
        ("Validation Accuracy", metric_text(accuracy, True)),
        ("Macro F1", metric_text(macro_f1, False)),
        ("Log Loss", metric_text(log_loss, False)),
        ("Checkpoint", f"{model_minute}'"),
    ]
    vx = [0.17, 0.39, 0.61, 0.83]
    for x, (label, value) in zip(vx, validation_items):
        ax.text(x, 0.198, value, ha="center", fontsize=15,
                fontweight="bold", color=navy)
        ax.text(x, 0.174, label, ha="center", fontsize=8.8, color=grey)

    # Safety / methodology boundary
    ax.text(
        0.5, 0.105,
        "Experimental research estimate based on historical StatsBomb match-state snapshots.",
        ha="center", fontsize=9.5, color=dark, fontweight="bold"
    )
    ax.text(
        0.5, 0.080,
        "These values are model estimates, not guaranteed outcomes and not fully calibrated production probabilities.",
        ha="center", fontsize=9.0, color=grey
    )
    ax.text(
        0.5, 0.045,
        "LiveMatch Intelligence | Predictive Intelligence | Match-state decision support",
        ha="center", fontsize=8.5, color=grey
    )

    return fig

